"""Signed tracked links for auction URLs (FR §6.1).

The token carries the destination generated by our server and an HMAC
signature; the redirect endpoint refuses tampered tokens and destinations
outside the allowed The Tender hosts.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
from dataclasses import dataclass
from urllib.parse import urlsplit

SOURCES = {"S": "SEARCH", "N": "NOTIFICATION", "C": "CAMPAIGN"}
_SIG_BYTES = 12


def _b64(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def _unb64(text: str) -> bytes:
    return base64.urlsafe_b64decode(text + "=" * (-len(text) % 4))


@dataclass(frozen=True)
class LinkTarget:
    user_id: int
    source: str  # SEARCH | NOTIFICATION | CAMPAIGN
    url: str
    auction_number: str | None


def allowed_hosts(base_url: str) -> set[str]:
    hosts = {"thetender.com.ua", "www.thetender.com.ua", "sandbox.mxuser.com"}
    host = urlsplit(base_url).hostname
    if host:
        hosts.add(host)
    return hosts


def is_allowed_destination(url: str, hosts: set[str]) -> bool:
    parts = urlsplit(url)
    return parts.scheme in ("https", "http") and (parts.hostname or "") in hosts


def make_token(
    key: bytes, user_id: int, url: str, source: str, auction_number: str | None = None
) -> str:
    code = {v: k for k, v in SOURCES.items()}[source]
    payload: dict = {"u": user_id, "s": code, "l": url}
    if auction_number:
        payload["n"] = auction_number
    body = _b64(json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode())
    sig = _b64(hmac.new(key, body.encode(), hashlib.sha256).digest()[:_SIG_BYTES])
    return f"{body}.{sig}"


def parse_token(key: bytes, token: str) -> LinkTarget | None:
    try:
        body, sig = token.split(".", 1)
        expected = _b64(hmac.new(key, body.encode(), hashlib.sha256).digest()[:_SIG_BYTES])
        if not hmac.compare_digest(sig, expected):
            return None
        data = json.loads(_unb64(body))
        return LinkTarget(
            user_id=int(data["u"]),
            source=SOURCES[data["s"]],
            url=str(data["l"]),
            auction_number=data.get("n"),
        )
    except (ValueError, KeyError, TypeError):
        return None


def tracked_url(
    public_base_url: str | None,
    key: bytes | None,
    user_id: int,
    url: str,
    source: str,
    auction_number: str | None = None,
) -> str:
    """Tracked redirect URL, or the original URL when tracking is not configured."""
    if not public_base_url or not key:
        return url
    return f"{public_base_url}/r/{make_token(key, user_id, url, source, auction_number)}"


_BOT_UA_MARKERS = ("bot", "crawler", "spider", "preview", "facebookexternalhit", "slurp")


def is_bot_user_agent(user_agent: str | None) -> bool:
    ua = (user_agent or "").lower()
    return not ua or any(marker in ua for marker in _BOT_UA_MARKERS)
