"""initial schema: users, roles, events, legal, privacy, bot sessions

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 13:31:35.727001
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sessions',
    sa.Column('telegram_user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id', name=op.f('pk_bot_sessions'))
    )
    op.create_table('legal_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.CheckConstraint("doc_type IN ('TERMS','PRIVACY')", name=op.f('ck_legal_documents_doc_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_documents')),
    sa.UniqueConstraint('doc_type', name=op.f('uq_legal_documents_doc_type'))
    )
    op.create_table('processed_updates',
    sa.Column('update_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('update_id', name=op.f('pk_processed_updates'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketing_opt_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('admin_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('system_notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_admin_settings'))
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_type_created', 'events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_events_user_created', 'events', ['user_id', 'created_at'], unique=False)
    op.create_table('legal_document_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stored_reference', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=False),
    sa.Column('require_reacceptance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','ARCHIVED')", name=op.f('ck_legal_document_versions_status_valid')),
    sa.ForeignKeyConstraint(['document_id'], ['legal_documents.id'], name=op.f('fk_legal_document_versions_document_id_legal_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_document_versions')),
    sa.UniqueConstraint('document_id', 'version', name='uq_legal_versions_doc_version')
    )
    op.create_index('uq_legal_versions_one_active', 'legal_document_versions', ['document_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('manager_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('consultation_notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manager_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_manager_settings'))
    )
    op.create_table('privacy_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), server_default='DATA_DELETION', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='NEW', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('handled_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('NEW','IN_PROGRESS','COMPLETED')", name=op.f('ck_privacy_requests_status_valid')),
    sa.CheckConstraint("type IN ('DATA_DELETION')", name=op.f('ck_privacy_requests_type_valid')),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], name=op.f('fk_privacy_requests_handled_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_privacy_requests_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_requests'))
    )
    op.create_index('uq_privacy_requests_one_open', 'privacy_requests', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('NEW','IN_PROGRESS')"))
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('MANAGER','ADMIN')", name=op.f('ck_user_roles_role_valid')),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_user_roles_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_role')
    )
    op.create_table('user_legal_acceptances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('legal_document_version_id', sa.BigInteger(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_document_version_id'], ['legal_document_versions.id'], name=op.f('fk_user_legal_acceptances_legal_document_version_id_legal_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_legal_acceptances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_legal_acceptances')),
    sa.UniqueConstraint('user_id', 'legal_document_version_id', name='uq_acceptance_user_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_legal_acceptances')
    op.drop_table('user_roles')
    op.drop_index('uq_privacy_requests_one_open', table_name='privacy_requests', postgresql_where=sa.text("status IN ('NEW','IN_PROGRESS')"))
    op.drop_table('privacy_requests')
    op.drop_table('manager_settings')
    op.drop_index('uq_legal_versions_one_active', table_name='legal_document_versions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('legal_document_versions')
    op.drop_index('ix_events_user_created', table_name='events')
    op.drop_index('ix_events_type_created', table_name='events')
    op.drop_table('events')
    op.drop_table('admin_settings')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('processed_updates')
    op.drop_table('legal_documents')
    op.drop_table('bot_sessions')
    # ### end Alembic commands ###
