"""consultations

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 12:42:24.916893
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='NEW', nullable=False),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('claimed_by', sa.BigInteger(), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result IS NULL OR result IN ('INTERESTED','DECLINED')", name=op.f('ck_consultation_requests_result_valid')),
    sa.CheckConstraint("status IN ('NEW','IN_PROGRESS','COMPLETED','CLOSED_BY_ADMIN')", name=op.f('ck_consultation_requests_status_valid')),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], name=op.f('fk_consultation_requests_claimed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_consultation_requests_closed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consultation_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_requests'))
    )
    op.create_index('ix_consultation_claimed_by', 'consultation_requests', ['claimed_by', 'status'], unique=False)
    op.create_index('ix_consultation_status_created', 'consultation_requests', ['status', 'created_at'], unique=False)
    op.create_index('uq_consultation_one_open_per_user', 'consultation_requests', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('NEW','IN_PROGRESS')"))
    op.create_table('consultation_notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='MANAGER', nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('MANAGER','ADMIN_FALLBACK')", name=op.f('ck_consultation_notifications_kind_valid')),
    sa.CheckConstraint("status IN ('SENT','FAILED')", name=op.f('ck_consultation_notifications_status_valid')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_consultation_notifications_recipient_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['consultation_requests.id'], name=op.f('fk_consultation_notifications_request_id_consultation_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_notifications'))
    )
    op.create_index('ix_consultation_notifications_request', 'consultation_notifications', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consultation_notifications_request', table_name='consultation_notifications')
    op.drop_table('consultation_notifications')
    op.drop_index('uq_consultation_one_open_per_user', table_name='consultation_requests', postgresql_where=sa.text("status IN ('NEW','IN_PROGRESS')"))
    op.drop_index('ix_consultation_status_created', table_name='consultation_requests')
    op.drop_index('ix_consultation_claimed_by', table_name='consultation_requests')
    op.drop_table('consultation_requests')
    # ### end Alembic commands ###
