"""admin dashboard

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-09 13:09:58.792127
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invitations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invited_user_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','ACCEPTED','DECLINED','CANCELLED')", name=op.f('ck_admin_invitations_status_valid')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_admin_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], name=op.f('fk_admin_invitations_invited_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_invitations'))
    )
    op.create_index('uq_admin_invitations_one_pending', 'admin_invitations', ['invited_user_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('admin_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_admin_sessions_token_hash'))
    )
    op.add_column('legal_document_versions', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('legal_document_versions', sa.Column('file_sha256', sa.String(length=64), nullable=True))
    op.add_column('legal_document_versions', sa.Column('file_content', sa.LargeBinary(), nullable=True))
    op.add_column('legal_document_versions', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_legal_document_versions_created_by_users'), 'legal_document_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_legal_document_versions_created_by_users'), 'legal_document_versions', type_='foreignkey')
    op.drop_column('legal_document_versions', 'created_by')
    op.drop_column('legal_document_versions', 'file_content')
    op.drop_column('legal_document_versions', 'file_sha256')
    op.drop_column('legal_document_versions', 'file_name')
    op.drop_table('admin_sessions')
    op.drop_index('uq_admin_invitations_one_pending', table_name='admin_invitations', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('admin_invitations')
    # ### end Alembic commands ###
