"""access blocking

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-10 06:25:51.580198
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_phones',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_blocked_phones_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('phone', name=op.f('pk_blocked_phones'))
    )
    op.add_column('users', sa.Column('access_blocked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('access_blocked_by', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('access_block_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('access_block_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_users_access_blocked_by_users'), 'users', 'users', ['access_blocked_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_access_blocked_by_users'), 'users', type_='foreignkey')
    op.drop_column('users', 'access_block_notified_at')
    op.drop_column('users', 'access_block_reason')
    op.drop_column('users', 'access_blocked_by')
    op.drop_column('users', 'access_blocked_at')
    op.drop_table('blocked_phones')
    # ### end Alembic commands ###
