"""campaigns

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-10 10:16:16.076585
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('button_text', sa.String(length=64), nullable=True),
    sa.Column('button_url', sa.Text(), nullable=True),
    sa.Column('audience_type', sa.String(length=16), server_default='ALL', nullable=False),
    sa.Column('selected_user_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('audience_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('opted_out_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unreachable_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('recipients_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("audience_type IN ('ALL','SELECTED')", name=op.f('ck_campaigns_audience_type_valid')),
    sa.CheckConstraint("status IN ('DRAFT','SENDING','DONE')", name=op.f('ck_campaigns_status_valid')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_campaigns_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('campaign_recipients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','SENDING','SENT','FAILED','SKIPPED')", name=op.f('ck_campaign_recipients_status_valid')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_recipients_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaign_recipients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_recipients')),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_recipient')
    )
    op.create_index('ix_campaign_recipients_campaign', 'campaign_recipients', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_campaign_recipients_queue', 'campaign_recipients', ['status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaign_recipients_queue', table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_campaign', table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
